### ISSUE TITLE
I18n is not working

### ISSUE THREAD

**Issue by tomekw** [jgdavey/tabletastic#16]
Hi,

I have tried to change all my "Destroy" links to "Delete", followed instructions in the README, but with no luck.

**Comment by jgdavey** [comment]
The i18n stuff was in master, but not released yet. I've just released v0.2.2, which should get you up and running:

```
gem 'tabletastic', '~> 0.2.2'
```

You may need to run `bundle update tabletastic`

**Comment by pincheira** [comment]
I updated the gem to the version 0.2.2 and still getting the same issue. Weird that it works for "confirmation" but not for other actions like "show", "edit" and "destroy".

**Comment by pincheira** [comment]
My bad, in the project there was an extra myapp/config/locales/tabletastic.en.yml. I was only looking at the tabletastic section inside myapp/config/locales/application.en.yml
